runs:
  using: composite
  steps:

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.12"
      cache: pip
      cache-dependency-path: requirements*.txt

  - name: Install Python dependencies
    run: pip install -r requirements.txt -r requirements_dev.txt
    shell: bash
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PIP_PROGRESS_BAR: "off"
