runs:
  using: composite
  steps:

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: "3.11"
      cache: pip
      cache-dependency-path: requirements*.txt

  - name: Install Python dependencies
    run: |
      pip install --progress-bar off -r requirements.txt
      pip install --progress-bar off -r requirements_dev.txt
    shell: bash
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
