name: CI

on: push

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependendencies
      uses: ./.github/actions/setup

    - name: Lint
      run: make lint

    - name: Typecheck
      run: make typecheck

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      uses: ./.github/actions/setup

    # cracklib provides the wordlist used in m38, but we skip this dependency
    # because we also skip the test that requires it.
    - name: Install system dependencies
      run: sudo apt-get -y install cracklib-runtime
      if: false

    - name: Test
      run: python -m unittest -v --locals --buffer
